language: rust
sudo: false
cache: cargo
rust:
  - stable
  - beta
  - nightly
  - 1.33.0
os:
  - linux
  - osx

script:
  - cargo build -v
  - cargo build -v --no-default-features
  - cargo test -v
  - cargo test -v --no-default-features
